// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conversation.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageResponse struct {
	Sentiment            string   `protobuf:"bytes,1,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	TicketCreated        bool     `protobuf:"varint,2,opt,name=ticket_created,json=ticketCreated,proto3" json:"ticket_created,omitempty"`
	TicketStatus         string   `protobuf:"bytes,3,opt,name=ticket_status,json=ticketStatus,proto3" json:"ticket_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetSentiment() string {
	if m != nil {
		return m.Sentiment
	}
	return ""
}

func (m *MessageResponse) GetTicketCreated() bool {
	if m != nil {
		return m.TicketCreated
	}
	return false
}

func (m *MessageResponse) GetTicketStatus() string {
	if m != nil {
		return m.TicketStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "lumina.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "lumina.MessageResponse")
}

func init() {
	proto.RegisterFile("conversation.proto", fileDescriptor_d6ae46d001825652)
}

var fileDescriptor_d6ae46d001825652 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x40, 0xad, 0x42, 0x6b, 0x07, 0x8d, 0xb0, 0x82, 0x0d, 0xa5, 0x07, 0x89, 0x08, 0x9e, 0x12,
	0x54, 0xfc, 0x03, 0xe6, 0x24, 0x18, 0x90, 0xd4, 0x53, 0x2f, 0x61, 0xb3, 0x19, 0xea, 0xa2, 0xd9,
	0x8d, 0x3b, 0xb3, 0xbd, 0xf8, 0xe7, 0xa5, 0xbb, 0xf5, 0x0b, 0x8f, 0xf3, 0x76, 0x78, 0xec, 0x1b,
	0x10, 0xca, 0x9a, 0x0d, 0x3a, 0x92, 0xac, 0xad, 0xc9, 0x07, 0x67, 0xd9, 0x8a, 0xf1, 0x9b, 0xef,
	0xb5, 0x91, 0x59, 0x09, 0x49, 0x85, 0x44, 0x72, 0x8d, 0x35, 0xbe, 0x7b, 0x24, 0x16, 0x33, 0x98,
	0x78, 0x42, 0xd7, 0xe8, 0x2e, 0x1d, 0x9d, 0x8f, 0xae, 0xa6, 0xf5, 0x78, 0x3b, 0x3e, 0x74, 0x22,
	0x85, 0x89, 0xb2, 0x86, 0xd1, 0x70, 0xba, 0x1f, 0x1e, 0xbe, 0xc6, 0xec, 0x03, 0x4e, 0xbe, 0x25,
	0x34, 0x58, 0x43, 0x28, 0x16, 0x30, 0x25, 0x34, 0xac, 0xfb, 0xed, 0x7a, 0xf4, 0xfc, 0x00, 0x71,
	0x09, 0x09, 0x6b, 0xf5, 0x8a, 0xdc, 0x28, 0x87, 0x92, 0xb1, 0x0b, 0xc6, 0xc3, 0xfa, 0x38, 0xd2,
	0x32, 0x42, 0x71, 0x01, 0x3b, 0xd0, 0x10, 0x4b, 0xf6, 0x94, 0x1e, 0x04, 0xd1, 0x51, 0x84, 0xcb,
	0xc0, 0x6e, 0x56, 0x70, 0x5a, 0xfe, 0xea, 0x5b, 0xa2, 0xdb, 0x68, 0x85, 0xa2, 0x84, 0xe4, 0xc9,
	0x59, 0x85, 0x44, 0xbb, 0xaf, 0x89, 0xb3, 0x3c, 0x36, 0xe7, 0x7f, 0x83, 0xe7, 0xb3, 0x7f, 0x3c,
	0x36, 0x64, 0x7b, 0xf7, 0x8b, 0xd5, 0x7c, 0xad, 0xf9, 0xc5, 0xb7, 0xb9, 0xb2, 0x7d, 0x51, 0x55,
	0xcf, 0xd7, 0x77, 0xc5, 0x63, 0x58, 0x2e, 0x86, 0xb6, 0x1d, 0x87, 0x53, 0xde, 0x7e, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xd4, 0xda, 0x97, 0x53, 0x60, 0x01, 0x00, 0x00,
}
